apiVersion: v1
kind: Service
metadata:
  name: fastapi-proxy
  namespace: rathor-inference
spec:
  selector:
    app: fastapi-proxy
  ports:
  - port: 80
    targetPort: 8000
    name: http
  type: ClusterIP
